export const tweetCategories = [
    'Technology',
    'Data Science',
    'Home',
    'HealthTech',
    'Code',
    'Business',
    'Education',
    'Entertainment',
    'Environment',
    'Fashion',
    'Finance',
    'Food',
    'Gaming',
    'Health',
    'Lifestyle',
    'Marketing',
    'Music',
    'News',
    'Politics',
    'Computer Science',
    'Science',
    'Sports',
    'Travel',
    'Wellness',
    'Art',
    'Automotive',
    'Books',
    'Culture',
    'DIY',
    'Fitness',
    'History',
    'Nature',
    'Parenting',
    'Pets',
    'Photography',
    'Productivity',
    'Relationships',
    'Spirituality',
    'Startups',
    'Writing',
    'Artificial Intelligence',
    'Blockchain',
    'Cloud Computing',
    'Cybersecurity',
    'E-commerce',
    'Economics',
    'Energy',
    'Entrepreneurship',
    'Gadgets',
    'Hardware',
    'Human Resources',
    'Innovation',
    'Investment',
    'Leadership',
    'Legal',
    'Logistics',
    'Machine Learning',
    'Management',
    'Manufacturing',
    'Media',
    'Mobile',
    'Non-Profit',
    'Operations',
    'Personal Development',
    'Philanthropy',
    'Public Speaking',
    'Real Estate',
    'Retail',
    'Robotics',
    'Sales',
    'Self Improvement',
    'Social Media',
    'Software Development',
    'Space',
    'Sustainability',
    'Tech Reviews',
    'Transportation',
    'User Experience',
    'User Interface',
    'Virtual Reality',
    'Wearables',
    'Web Development',
    'Agriculture',
    'Anthropology',
    'Archaeology',
    'Architecture',
    'Astronomy',
    'Biotechnology',
    'Chemistry',
    'Cinematography',
    'Classical Music',
    'Comedy',
    'Cryptocurrency',
    'Culinary Arts',
    'Culture Studies',
    'Dance',
    'Design',
    'Earth Science',
    'Ecology',
    'Engineering',
    'Ethics',
    'Film',
    'Fine Arts',
    'Forestry',
    'Genetics',
    'Geography',
    'Geology',
    'Graphic Design',
    'History of Science',
    'Information Technology',
    'Journalism',
    'Language Learning',
    'Linguistics',
    'Literature',
    'Marine Biology',
    'Mathematics',
    'Meteorology',
    'Microbiology',
    'Modern Art',
    'Nanotechnology',
    'Neuroscience',
    'Oceanography',
    'Optics',
    'Performing Arts',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Quantum Computing',
    'Religious Studies',
    'Renewable Energy',
    'Sociology',
    'Software Engineering',
    'Sound Engineering',
    'Space Exploration',
    'Theater',
    'Urban Planning',
    'Veterinary Science',
    'Wildlife Conservation',
    'Zoology',
    '3D Printing',
    'Aeronautics',
    'Astrophysics',
    'Bioinformatics',
    'Biophysics',
    'Cartography',
    'Cognitive Science',
    'Conservation',
    'Criminology',
    'Data Analytics',
    'Data Visualization',
    'Digital Art',
    'Digital Marketing',
    'Environmental Science',
    'Evolutionary Biology',
    'Film Production',
    'Fisheries',
    'Genomics',
    'Horticulture',
    'Hydrology',
    'Immunology',
    'Industrial Design',
    'Information Science',
    'Informatics',
    'Integrated Circuits',
    'Library Science',
    'Material Science',
    'Media Studies',
    'Molecular Biology',
    'Music Production',
    'Network Security',
    'Nuclear Physics',
    'Paleontology',
    'Pathology',
    'Petroleum Engineering',
    'Pharmacology',
    'Photonics',
    'Plant Science',
    'Political Economy',
    'Public Policy',
    'Quantum Physics',
    'Radio Astronomy',
    'Remote Sensing',
    'Seismology',
    'Software Architecture',
    'Speech Recognition',
    'Systems Biology',
    'Telecommunications',
    'Toxicology',
    'Transhumanism',
    'UX Design',
    'Virology',
    'Water Resources',
    'Web Analytics',
    'Web Security',
]
