export const itemCategories = [
    'Technology',
    'Data Science',
    'Home',
    'HealthTech',
    'Software Development',
    'Business',
    'Education',
    'Entertainment',
    'Environment',
    'Fashion',
    'Finance',
    'Food',
    'Gaming',
    'Health',
    'Lifestyle',
    'Marketing',
    'Music',
    'News',
    'Politics',
    'Computer Science',
    'Science',
    'Sports',
    'Travel',
    'Wellness',
    'Art',
    'Automotive',
    'Books',
    'Culture',
    'DIY',
    'Fitness',
    'History',
    'Nature',
    'Parenting',
    'Pets',
    'Photography',
    'Productivity',
    'Relationships',
    'Spirituality',
    'Startups',
    'Writing',
    'Artificial Intelligence',
    'Blockchain',
    'Cloud Computing',
    'Cybersecurity',
    'E-commerce',
    'Economics',
    'Energy',
    'Entrepreneurship',
    'Gadgets',
    'Hardware',
    'Human Resources',
    'Innovation',
    'Investment',
    'Leadership',
    'Legal',
    'Logistics',
    'Management',
    'Manufacturing',
    'Media',
    'Mobile',
    'Non-Profit',
    'Operations',
    'Personal Development',
    'Philanthropy',
    'Public Speaking',
    'Real Estate',
    'Retail',
    'Robotics',
    'Sales',
    'Social Media',
    'Space',
    'Sustainability',
    'Transportation',
    'User Experience',
    'User Interface',
    'Virtual Reality',
    'Wearables',
    'Agriculture',
    'Anthropology',
    'Archaeology',
    'Architecture',
    'Astronomy',
    'Biotechnology',
    'Chemistry',
    'Cinematography',
    'Classical Music',
    'Comedy',
    'Culinary Arts',
    'Dance',
    'Design',
    'Earth Science',
    'Ecology',
    'Engineering',
    'Ethics',
    'Film',
    'Forestry',
    'Genetics',
    'Geography',
    'Geology',
    'History of Science',
    'Journalism',
    'Language Learning',
    'Linguistics',
    'Literature',
    'Marine Biology',
    'Mathematics',
    'Meteorology',
    'Microbiology',
    'Nanotechnology',
    'Neuroscience',
    'Oceanography',
    'Optics',
    'Performing Arts',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Health',
    'Quantum Computing',
    'Religious Studies',
    'Sociology',
    'Sound Engineering',
    'Theater',
    'Urban Planning',
    'Veterinary Science',
    'Wildlife Conservation',
    'Zoology',
    '3D Printing',
    'Aeronautics',
    'Astrophysics',
    'Bioinformatics',
    'Biophysics',
    'Cartography',
    'Cognitive Science',
    'Conservation',
    'Criminology',
    'Data Analytics',
    'Digital Marketing',
    'Environmental Science',
    'Evolutionary Biology',
    'Fisheries',
    'Genomics',
    'Horticulture',
    'Hydrology',
    'Immunology',
    'Information Science',
    'Informatics',
    'Integrated Circuits',
    'Material Science',
    'Molecular Biology',
    'Music Production',
    'Nuclear Physics',
    'Paleontology',
    'Pathology',
    'Petroleum Engineering',
    'Pharmacology',
    'Photonics',
    'Plant Science',
    'Public Policy',
    'Radio Astronomy',
    'Remote Sensing',
    'Seismology',
    'Speech Recognition',
    'Systems Biology',
    'Telecommunications',
    'Toxicology',
    'Transhumanism',
    'Virology',
    'Water Resources',
    'Web Analytics',
    'None',
]
